### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-avatars#1]
I'm thinking about using some console tool to process images like `imagemagick` for cropping, but not sure if that is okay with the way app is deployed. Are there any restrictions or requirements on tools?

**Comment by j3k0** [comment]
No special requirements, it should be installable on the node:0.10.33-slim docker image (which I believe is either debian or ubuntu based). You can try editing the `Dockerfile` and run `docker-compose build`
